import type { Metadata } from "next";
import Link from "next/link";
import { getCachedAnalysisById } from "@/lib/analysis-cache";
import { loadStoryIndex } from "@/lib/content";
import { ScoreGauge } from "@/components/job-fit/ScoreGauge";
import { StrengthsList } from "@/components/job-fit/StrengthsList";
import { WeaknessesList } from "@/components/job-fit/WeaknessesList";
import { RelevantStories } from "@/components/job-fit/RelevantStories";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Sparkles } from "lucide-react";
import type { HeroStoryMeta } from "@/lib/types";

/** Validates that the ID matches the expected nanoid(10) format. */
function isValidId(id: string): boolean {
  return /^[A-Za-z0-9_-]{10}$/.test(id);
}

interface Props {
  params: { id: string };
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const cached = isValidId(params.id) ? await getCachedAnalysisById(params.id) : null;
  if (!cached) return {};
  const desc = `${cached.roleHint ? `${cached.roleHint} · ` : ""}${cached.result.headline}`;
  return {
    title: `Job Fit: ${cached.result.grade} (${cached.result.score}/100) — Satori Canton`,
    description: desc,
    openGraph: {
      title: `Job Fit: ${cached.result.grade} (${cached.result.score}/100)`,
      description: desc,
    },
  };
}

export default async function AnalysisPage({ params }: Props) {
  const cached = isValidId(params.id) ? await getCachedAnalysisById(params.id) : null;

  if (!cached) {
    return (
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <div className="flex flex-col items-center justify-center py-24 gap-4 text-center">
          <div className="text-4xl text-muted-foreground/40" aria-hidden>
            🔗
          </div>
          <h1 className="font-serif text-2xl font-normal">
            This analysis has expired
          </h1>
          <p className="text-sm text-muted-foreground max-w-sm">
            Analysis links are available for 7 days. The link you followed is
            no longer active.
          </p>
          <Button size="lg" asChild className="gap-2 mt-2">
            <Link href="/job-fit">
              <Sparkles className="h-4 w-4" />
              Evaluate your own role
            </Link>
          </Button>
        </div>
      </div>
    );
  }

  const { result, roleHint } = cached;

  let allStories: HeroStoryMeta[] = [];
  try {
    allStories = await loadStoryIndex();
  } catch {
    // Non-fatal — stories section simply won't render
  }

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
      {/* Page header */}
      <div className="mb-8">
        <h1 className="font-serif text-4xl font-normal mb-3">
          Job Fit Analysis
        </h1>
        {roleHint && (
          <p className="text-sm text-muted-foreground mt-1 mb-2">
            Evaluated for:{" "}
            <span className="text-foreground/80">{roleHint}</span>
          </p>
        )}
        <p className="text-muted-foreground leading-relaxed">
          AI-powered assessment of how Satori Canton&apos;s background fits
          this role. Generated by the{" "}
          <Link
            href="/job-fit"
            className="underline underline-offset-4 hover:text-foreground transition-colors"
          >
            Job Fit Evaluator
          </Link>
          .
        </p>
      </div>

      <div className="space-y-8">
        {/* Score + headline */}
        <div className="flex flex-col sm:flex-row items-center sm:items-start gap-6 p-6 rounded-xl border border-border/50 bg-card">
          <ScoreGauge score={result.score} grade={result.grade} />
          <div className="flex-1 text-center sm:text-left">
            <h2 className="font-serif text-2xl font-normal mb-2">
              {result.headline}
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed mb-4">
              {result.roleAlignment}
            </p>
            <div className="p-3 rounded-lg bg-muted/50 border border-border/40 text-sm text-muted-foreground italic">
              {result.recommendation}
            </div>
          </div>
        </div>

        {/* Strengths */}
        <div>
          <h3 className="font-serif text-xl font-normal mb-4">Strengths</h3>
          <StrengthsList strengths={result.strengths} />
        </div>

        {/* Weaknesses */}
        {result.weaknesses.length > 0 && (
          <div>
            <h3 className="font-serif text-xl font-normal mb-4">
              Gaps &amp; Weaknesses
            </h3>
            <p className="text-xs text-muted-foreground mb-3 italic">
              Honest assessment — these are real gaps, not spin.
            </p>
            <WeaknessesList weaknesses={result.weaknesses} />
          </div>
        )}

        {/* Relevant stories — filter nulls for removed stories */}
        {result.relevantStoryIds.length > 0 && allStories.length > 0 && (
          <div>
            <h3 className="font-serif text-xl font-normal mb-4">
              Relevant Case Studies
            </h3>
            <RelevantStories
              storyIds={result.relevantStoryIds}
              allStories={allStories}
            />
          </div>
        )}

        <Separator className="opacity-30" />

        {/* CTA */}
        <div className="text-center space-y-2">
          <p className="text-sm text-muted-foreground">
            Paste your own job description. Results in ~15 seconds.
          </p>
          <Button size="lg" asChild className="gap-2">
            <Link href="/job-fit">
              <Sparkles className="h-4 w-4" />
              Run your own analysis
            </Link>
          </Button>
        </div>
      </div>
    </div>
  );
}
